# filename: create-db.py | Code Generated by Sidekick is for learning and experimentation purposes only.
from pathlib import Path
import sqlite3

DATABASE_PATH = Path(__file__).resolve().parent / "data" / "database.sqlite"
DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)

with sqlite3.connect(DATABASE_PATH) as connection:
    cursor = connection.cursor()

    cursor.executescript("""
    DROP TABLE IF EXISTS sales;
    DROP TABLE IF EXISTS customers;
    DROP TABLE IF EXISTS employees;

    CREATE TABLE sales (
        id INTEGER PRIMARY KEY,
        region TEXT NOT NULL,
        product TEXT NOT NULL,
        revenue REAL NOT NULL,
        date TEXT NOT NULL,
        units_sold INTEGER NOT NULL
    );

    CREATE TABLE customers (
        id INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        industry TEXT NOT NULL,
        churn_date TEXT,
        satisfaction_score REAL
    );

    CREATE TABLE employees (
        id INTEGER PRIMARY KEY,
        department TEXT NOT NULL,
        satisfaction_score REAL NOT NULL,
        tenure_years REAL NOT NULL
    );
    """)

    regions = {
        "East": 12000,
        "West": 9500,
        "South": 8000,
        "Central": 11000,
    }

    products = {
        "Software": 0.60,
        "Services": 0.40,
    }

    monthly_factors = [
        0.85, 0.90, 0.95, 1.00,
        1.05, 1.00, 1.10, 1.05,
        1.15, 1.30, 1.40, 1.55,
    ]

    sales_rows = []
    sale_id = 1

    for month, factor in enumerate(monthly_factors, start=1):
        for region, base_revenue in regions.items():
            for product, share in products.items():
                revenue = round(base_revenue * factor * share, 2)
                unit_price = 500 if product == "Software" else 700
                units_sold = max(1, round(revenue / unit_price))

                sales_rows.append((
                    sale_id,
                    region,
                    product,
                    revenue,
                    f"2026-{month:02d}-15",
                    units_sold,
                ))
                sale_id += 1

    cursor.executemany("""
    INSERT INTO sales
        (id, region, product, revenue, date, units_sold)
    VALUES (?, ?, ?, ?, ?, ?)
    """, sales_rows)

    customer_names = [
        ("Acme Corp", "Technology"),
        ("Northwind Ltd", "Retail"),
        ("Contoso Inc", "Healthcare"),
        ("Globex Corporation", "Manufacturing"),
        ("Initech", "Technology"),
        ("Umbrella Health", "Healthcare"),
        ("Stark Industries", "Manufacturing"),
        ("Wayne Enterprises", "Financial Services"),
        ("Wonka Foods", "Consumer Products"),
        ("Hooli", "Technology"),
        ("Soylent Corp", "Consumer Products"),
        ("Massive Dynamic", "Technology"),
        ("Cyberdyne Systems", "Manufacturing"),
        ("Oceanic Airlines", "Transportation"),
        ("Vandelay Industries", "Manufacturing"),
        ("Prestige Worldwide", "Entertainment"),
        ("Duff Brewing", "Consumer Products"),
        ("Tyrell Corporation", "Technology"),
        ("Gringotts Bank", "Financial Services"),
        ("Monarch Solutions", "Healthcare"),
    ]

    churn_dates = {
        3: "2026-02-15",
        7: "2026-04-20",
        11: "2026-07-10",
        15: "2026-09-05",
        19: "2026-11-18",
    }

    customer_rows = []

    for customer_id, (name, industry) in enumerate(customer_names, start=1):
        churn_date = churn_dates.get(customer_id)
        satisfaction = 2.8 if churn_date else 4.3

        customer_rows.append((
            customer_id,
            name,
            industry,
            churn_date,
            satisfaction,
        ))

    cursor.executemany("""
    INSERT INTO customers
        (id, name, industry, churn_date, satisfaction_score)
    VALUES (?, ?, ?, ?, ?)
    """, customer_rows)

    employee_rows = [
        (1, "Consulting", 4.2, 3.5),
        (2, "Consulting", 4.5, 5.0),
        (3, "Audit", 3.8, 4.0),
        (4, "Audit", 4.1, 6.5),
        (5, "Tax", 4.6, 2.0),
        (6, "Tax", 4.3, 7.0),
        (7, "Technology", 4.0, 3.0),
        (8, "Technology", 4.4, 8.0),
    ]

    cursor.executemany("""
    INSERT INTO employees
        (id, department, satisfaction_score, tenure_years)
    VALUES (?, ?, ?, ?)
    """, employee_rows)

    connection.commit()

    sales_count = cursor.execute(
        "SELECT COUNT(*) FROM sales"
    ).fetchone()[0]

    customer_count = cursor.execute(
        "SELECT COUNT(*) FROM customers"
    ).fetchone()[0]

    churned_count = cursor.execute(
        "SELECT COUNT(*) FROM customers WHERE churn_date IS NOT NULL"
    ).fetchone()[0]

print(f"Created database: {DATABASE_PATH}")
print(f"Sales rows: {sales_count}")
print(f"Customer rows: {customer_count}")
print(f"Churned customers: {churned_count} of {customer_count}")
print("Database seeding complete.")
